In [2]:
from torch_geometric.datasets import QM9
dataset = QM9(root="./QM9_reduced/")

Extracting QM9_reduced/raw/qm9.zip
Processing...
100%|██████████| 133885/133885 [00:39<00:00, 3411.46it/s]
Done!


In [8]:
dataset[0].x

tensor([[0., 1., 0., 0., 0., 6., 0., 0., 0., 0., 4.],
        [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [7]:
import pandas as pd
df = pd.read_csv("./QM9_all/raw/gdb9.sdf.csv")
df

mol_id          A           B           C      mu  alpha    homo  \
0            gdb_1  157.71180  157.709970  157.706990  0.0000  13.21 -0.3877   
1            gdb_2  293.60975  293.541110  191.393970  1.6256   9.46 -0.2570   
2            gdb_3  799.58812  437.903860  282.945450  1.8511   6.31 -0.2928   
3            gdb_4    0.00000   35.610036   35.610036  0.0000  16.28 -0.2845   
4            gdb_5    0.00000   44.593883   44.593883  2.8937  12.99 -0.3604   
...            ...        ...         ...         ...     ...    ...     ...   
133880  gdb_133881    3.59483    2.198990    1.904230  1.6637  69.37 -0.2254   
133881  gdb_133882    3.65648    2.142370    1.904390  1.2976  69.52 -0.2393   
133882  gdb_133883    3.67118    2.143140    1.895010  1.2480  73.60 -0.2233   
133883  gdb_133884    3.52845    2.151310    1.865820  1.9576  77.40 -0.2122   
133884  gdb_133885    3.64015    2.217640    1.937930  0.8626  69.48 -0.2316   

          lumo     gap        r2      zpve          u0        u298  \
0       0.1171  0.5048   35.3641  0.044749  -40.478930  -40.476062   
1       0.0829  0.3399   26.1563  0.034358  -56.525887  -56.523026   
2       0.0687  0.3615   19.0002  0.021375  -76.404702  -76.401867   
3       0.0506  0.3351   59.5248  0.026841  -77.308427  -77.305527   
4       0.0191  0.3796   48.7476  0.016601  -93.411888  -93.409370   
...        ...     ...       ...       ...         ...         ...   
133880  0.0588  0.2842  760.7472  0.127406 -400.633868 -400.628599   
133881  0.0608  0.3002  762.6354  0.127495 -400.629713 -400.624444   
133882  0.0720  0.2953  780.3553  0.140458 -380.753918 -380.748619   
133883  0.0881  0.3003  803.1904  0.152222 -364.720374 -364.714974   
133884  0.0742  0.3058  756.3557  0.127862 -400.633052 -400.627892   

              h298        g298      cv      u0_atom    u298_atom    h298_atom  \
0       -40.475117  -40.498597   6.469  -395.999595  -398.643290  -401.014647   
1       -56.522082  -56.544961   6.316  -276.861363  -278.620271  -280.399259   
2       -76.400922  -76.422349   6.002  -213.087624  -213.974294  -215.159658   
3       -77.304583  -77.327429   8.574  -385.501997  -387.237686  -389.016047   
4       -93.408425  -93.431246   6.278  -301.820534  -302.906752  -304.091489   
...            ...         ...     ...          ...          ...          ...   
133880 -400.627654 -400.663098  23.658 -1603.983913 -1614.898804 -1623.788097   
133881 -400.623500 -400.658942  23.697 -1601.376613 -1612.291504 -1621.181424   
133882 -380.747675 -380.783148  23.972 -1667.045429 -1678.830048 -1688.312964   
133883 -364.714030 -364.749650  24.796 -1794.600439 -1807.210860 -1817.286772   
133884 -400.626948 -400.662186  23.434 -1603.471865 -1614.455155 -1623.345075   

          g298_atom  
0       -372.471772  
1       -259.338802  
2       -201.407171  
3       -365.800724  
4       -288.720028  
...             ...  
133880 -1492.819438  
133881 -1490.211511  
133882 -1549.143391  
133883 -1670.349892  
133884 -1492.247150  

[133885 rows x 20 columns]

In [42]:
x = dataset.x
x_list = [x[i][6:-1] for i in range(len(x))]

In [44]:
import torch
import numpy as np
a = torch.FloatTensor([0.,0.,0.,0.])
a

tensor([0., 0., 0., 0.])

In [45]:
print([x for x in x_list if x_list != a])

KeyboardInterrupt: 

In [46]:
x_list

[tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 tensor([0., 0., 0., 0.]),
 